apiVersion: v1
kind: ResourceQuota
metadata:
  name: example-resource-quota
  namespace: my-namespace
spec:
  hard:
    pods: "2"
    requests.memory: "256Mi"
    limits.memory: "512Mi"
    requests.cpu: "500m"
    limits.cpu: "1"
